package com.example.Integracion_Siom.model.symphony.v4.graphql;

public enum ServiceFilterTypeTO {

    SERVICE_INST_NAME,
    SERVICE_STATUS,
    SERVICE_DISCOVERY_METHOD,
    SERVICE_TYPE,
    SERVICE_INST_EXTERNAL_ID,
    SERVICE_INST_CUSTOMER_NAME,
    PROPERTY,
    LOCATION_INST,
    LOCATION_INST_EXTERNAL_ID,
    EQUIPMENT_IN_SERVICE

}